//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssinaturaDigital.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssinaturaDigital.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string @__Parametros__ {
            get {
                return ResourceManager.GetString("</Parametros>\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente cancelar as operações?.
        /// </summary>
        internal static string FormEnvioArquivos_btnCancelar_Click_Deseja_realmente_cancelar_as_operações_ {
            get {
                return ResourceManager.GetString("FormEnvioArquivos_btnCancelar_Click_Deseja_realmente_cancelar_as_operações_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja cancelar as operações e fechar?.
        /// </summary>
        internal static string FormEnvioArquivos_EnvioArquivosFormClosing_Deseja_cancelar_as_operações_e_fechar_ {
            get {
                return ResourceManager.GetString("FormEnvioArquivos_EnvioArquivosFormClosing_Deseja_cancelar_as_operações_e_fechar_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processo de assinatura digital em andamento....
        /// </summary>
        internal static string FormEnvioArquivos_IniciarProcessoProximoArquivo_Processo_de_assinatura_digital_em_andamento___ {
            get {
                return ResourceManager.GetString("FormEnvioArquivos_IniciarProcessoProximoArquivo_Processo_de_assinatura_digital_em" +
                        "_andamento___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguarde....
        /// </summary>
        internal static string FormErro_BtnReportarClick_Aguarde___ {
            get {
                return ResourceManager.GetString("FormErro_BtnReportarClick_Aguarde___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Certificado Digital necessário.
        /// </summary>
        internal static string FormErro_BtnReportarClick_Certificado_Digital_necessário {
            get {
                return ResourceManager.GetString("FormErro_BtnReportarClick_Certificado_Digital_necessário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        internal static string FormErro_BtnReportarClick_Erro {
            get {
                return ResourceManager.GetString("FormErro_BtnReportarClick_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar nenhum Certificado Digital. Por favor, insira um Certificado..
        /// </summary>
        internal static string FormErro_BtnReportarClick_Não_foi_possível_encontrar_nenhum_Certificado_Digital__Por_favor__insira_um_Certificado_ {
            get {
                return ResourceManager.GetString("FormErro_BtnReportarClick_Não_foi_possível_encontrar_nenhum_Certificado_Digital__" +
                        "Por_favor__insira_um_Certificado_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao enviar os detalhes do erro..
        /// </summary>
        internal static string FormErro_BtnReportarClick_Ocorreu_um_erro_ao_enviar_os_detalhes_do_erro_ {
            get {
                return ResourceManager.GetString("FormErro_BtnReportarClick_Ocorreu_um_erro_ao_enviar_os_detalhes_do_erro_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os detalhes do erro foram enviados com sucesso.
        /// </summary>
        internal static string FormErro_BtnReportarClick_Os_detalhes_do_erro_foram_enviados_com_sucesso {
            get {
                return ResourceManager.GetString("FormErro_BtnReportarClick_Os_detalhes_do_erro_foram_enviados_com_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gravar Log.
        /// </summary>
        internal static string FormLog_BtnGravarLogClick_Gravar_Log {
            get {
                return ResourceManager.GetString("FormLog_BtnGravarLogClick_Gravar_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvando....
        /// </summary>
        internal static string FormLog_BtnGravarLogClick_Salvando___ {
            get {
                return ResourceManager.GetString("FormLog_BtnGravarLogClick_Salvando___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivos salvos com sucesso!.
        /// </summary>
        internal static string FormSelecaoArquivos_BtnResumoLivroClick_Arquivos_salvos_com_sucesso_ {
            get {
                return ResourceManager.GetString("FormSelecaoArquivos_BtnResumoLivroClick_Arquivos_salvos_com_sucesso_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão: .
        /// </summary>
        internal static string FormSelecaoArquivos_FormSelecaoArquivos_Versão__ {
            get {
                return ResourceManager.GetString("FormSelecaoArquivos_FormSelecaoArquivos_Versão__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação.
        /// </summary>
        internal static string FormSelecaoArquivos_ImgAdicionarArquivosClick_Confirmação {
            get {
                return ResourceManager.GetString("FormSelecaoArquivos_ImgAdicionarArquivosClick_Confirmação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível remover o arquivo. Ele pode estar sendo utilizado por outro programa. Tente novamente..
        /// </summary>
        internal static string FormSelecaoArquivos_ImgAdicionarArquivosClick_Não_foi_possível_remover_o_arquivo__Ele_pode_estar_sendo_utilizado_por_outro_programa__Tente_novamente_ {
            get {
                return ResourceManager.GetString("FormSelecaoArquivos_ImgAdicionarArquivosClick_Não_foi_possível_remover_o_arquivo_" +
                        "_Ele_pode_estar_sendo_utilizado_por_outro_programa__Tente_novamente_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O máximo de arquivos permitido é 50. Para adicionar mais arquivos, por favor, envie os pendentes..
        /// </summary>
        internal static string FormSelecaoArquivos_ValidarTotalArquivos_O_máximo_de_arquivos_permitido_é_50__Para_adicionar_mais_arquivos__por_favor__envie_os_pendentes_ {
            get {
                return ResourceManager.GetString("FormSelecaoArquivos_ValidarTotalArquivos_O_máximo_de_arquivos_permitido_é_50__Par" +
                        "a_adicionar_mais_arquivos__por_favor__envie_os_pendentes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um Certificado Digital.
        /// </summary>
        internal static string FormSelecaoCertificadoDigital_btnSelecionar_Click_Selecione_um_Certificado_Digital {
            get {
                return ResourceManager.GetString("FormSelecaoCertificadoDigital_btnSelecionar_Click_Selecione_um_Certificado_Digita" +
                        "l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este certificado digital não está válido..
        /// </summary>
        internal static string FormSelecaoCertificadoDigital_BtnSelecionarClick_Este_certificado_digital_não_está_válido_ {
            get {
                return ResourceManager.GetString("FormSelecaoCertificadoDigital_BtnSelecionarClick_Este_certificado_digital_não_est" +
                        "á_válido_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Parametro id=&quot;2&quot; valor=&quot;C:\temp\log1&quot;/&gt;.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Parametro id=&quot;3&quot; valor=&quot;C:\temp\logValidador.log&quot;/&gt;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Parametro id=&quot;4&quot; valor=&quot;C:\Users\pedro.paulo\Desktop\xmls validador/&quot;/&gt;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Parametro id=&quot;5&quot; valor=&quot;Y&quot;/&gt;.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Parametro id=&quot;6&quot; valor=&quot;C:\Repositorios\AgNet\Código Fonte\Validador\Validador\bin\Debug&quot;/&gt;.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
    }
}
